### PR TITLE
added support for CSV-based credit card statements

### PR DESCRIPTION
**Pull request by gyp**
I think it'd make more sense to include it in this repo than to create a separate plugin for for it. If it's merged in it might make sense to do a version bump and a push to PyPI, too.

### CODE REVIEW

**Comment by abesto** [comment]
Nice! Agree it makes sense to include here, thank you for the PR. To clarify: credit card here means an _actual_ credit card, like AmEx, as opposed to debit cards OTP provides by default, correct? It might be best to clarify this in the README, nudge-nudge, wink-wink ;)

I don't have a credit card, so I'm gonna take your word that it works, and merge as is (after the above is clear). And sure, I'll take care of the version bump, PyPI release, as well as updating the listing on https://github.com/kedder/ofxstatement/blob/master/README.rst#known-plugins to include the credit card CSV thing.

**Comment by gyp** [comment]
You are absolutely correct, this is about actual credit cards -- for some reason those work differently than how debit cards do. I've added a small patch for the README to clarify that, too. Note that this *will not* work properly for CSV exports for debit card statements -- the order of columns is different and as there're no headers the only way to figure out which input format we're dealing with would be by applying some crude heuristics and I'd rather not do that.

Also, I am also using this to import things into YNAB and I did not know about bank2ynab -- cool project :)

**Comment by abesto** [comment]
Cool stuff, thank you! I'll take care of the bumps / updates over the weekend.

**Comment by abesto** [comment]
0.0.2 is up on https://pypi.org/project/ofxstatement-otp/. Thanks again!

**Pull request merged**
